/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Sample1 */

#ifndef _Included_Sample1
#define _Included_Sample1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Sample1
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Sample1_multiply
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
